name: day start # yml文件名

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 09 * * *'
  workflow_dispatch: # 手动触发工作流

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区
  TOKEN: ${{ secrets.TOKEN }} # 使用GitHub secret中的TOKEN变量

jobs:
  run-coupons: # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 使用v2版本，并修正分支指定方式

      - name: Setup Node.js
        uses: actions/setup-node@v2  # 安装Node.js
        with:
          node-version: '16'
          
      - name: Install Dependencies       
        run: npm install

      - name: Start Project
        run: npm start
        env:
          TOKEN: ${{ secrets.TOKEN }} # 在这一步中提供TOKEN环境变量给npm start
